### ISSUE TITLE
Focus on current window

### ISSUE THREAD

**Issue by Francesco7602** [zeroxoneafour/kwin-autotile#1]
It would be great to have a border window of different color on the focused window, it'll be very great!
Anyway, nice work you made here!

**Comment by zeroxoneafour** [comment]
I don't know if this is possible with just a KWin script, seems like it would need window decoration as well. I'm working on implementing something to show borders on selected windows, but unless you install a decoration theme like [this](https://www.pling.com/p/1678088/) then those borders will be the default KWin titlebar borders. If you install a theme like that, it should work maybe.

**Comment by b1scu1t** [comment]
This could be well beyond the scope of a 'script'. Bismuth uses a custom window decoration, which was more susceptible to breakage/crashes between KWin updates. You can work around the problem by sticking with Breeze (with the Breeze Classic colorscheme) or using what @zeroxoneafour suggested.

**Comment by zeroxoneafour** [comment]
Border setting implemented in the script settings, for what you want set the option to "border selected" or something like that
