### ISSUE TITLE
Add an option to resume tiling after moving window with mouse

### ISSUE THREAD

**Issue by willowew** [zeroxoneafour/kwin-autotile#11]
Currently, if a tiled window is moved with the mouse, it goes into floating mode. The other windows left untouched fill out the remaining space, as expected. If I recall correctly, Bismuth had an option where you could select if you wanted a window moved with the mouse to go into floating (as it does now) or to return to tiling mode. When enabling this option, the expected action would be similar to that with the Swap Left (or right, etc.) keyboard shortcut

Tested with v1.1.0

**Comment by zeroxoneafour** [comment]
Hold down (by default) the shift key while moving the window.
