### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Francesco7602** [zeroxoneafour/kwin-autotile#14]
Hello, sorry to bother you again but i found another bug.
When i try to open VS code with another window open, like Konsole, it doesn't tile.
But, instead, go up and in full screen mode.
What to do to see the bug:
1)Open konsole
2)Open VS Code
thanks in advance :)

**Comment by zeroxoneafour** [comment]
Is vscode in fullscreen mode? If it is, it should work if you take it out of fullscreen.

Fullscreen behavior with the tiling is kind of finicky right now.

**Comment by Francesco7602** [comment]
...my bad, vscode have an option that make the window open with the dimension of the last time it was open.
So is my fault.
My bad.

**Comment by zeroxoneafour** [comment]
Did this fix the issue? If it did, then I'll close this issue.

**Comment by Francesco7602** [comment]
ehhh
nope
because if i put vscode out of fullscreen is everything alright
But when is on full screen it doesn't work
