### ISSUE TITLE
When maximized, tile popup not work

### ISSUE THREAD

**Issue by Francesco7602** [zeroxoneafour/kwin-autotile#17]
https://user-images.githubusercontent.com/43477782/229288851-2c2d8f75-f8f3-4d91-9395-db26b7d9362e.mp4

Hello, sorry to bother you again but there is this bug where if i put a window in full size, the tile script don't work.
I put a video to make you see what i mean

**Comment by zeroxoneafour** [comment]
When a window is fullscreened, the script automatically puts it in the front above other tiled windows. Try disabling "tiled windows to the back" in settings and untile the fullscreen window before you fullscreen it. The script puts fullscreen windows back into their tiles when they exit fullscreen, so they will still take up a tiled space.

If this is not your issue, please provide a journalctl log.

**Comment by Francesco7602** [comment]
Ahhh okay okay.
Thanks, it works.

**Comment by zeroxoneafour** [comment]
I added a toggle to the settings as well to configure whether fullscreen windows are kept above, even when they are tiled. This setting may help you if you want to keep tiled windows below for the most part as well.

This is available in the autotile.kwinscript straight from github, I'll release it to the KDE store if the other features in this release are deemed stable enough.

**Comment by Francesco7602** [comment]
perfect!
Thank you
