### ISSUE TITLE
Makefile of v1.3.0 is broken

### ISSUE THREAD

**Issue by arghyasinha** [zeroxoneafour/kwin-autotile#20]
Unable to install `v1.3.0` using `make install`.
Output after `make` :
`mkdir -p pkg
mkdir -p pkg/contents/code
mkdir pkg/contents/config
mkdir pkg/contents/ui
cp res/metadata.json pkg/
cp res/main.xml pkg/contents/config/
cp res/config.ui pkg/contents/ui/
sed -i "s/%VERSION%/1.3.0/" pkg/metadata.json
tsc
make: tsc: No such file or directory
make: *** [Makefile:32: src] Error 127`

Output after `make install`:
`make: *** No rule to make target 'autotile.kwinscript', needed by 'install'.  Stop.`

Somehow the file `autotile.kwinscript` is not generated.

I tried to apply the commands manually:
`make res`
`make src`
`zip -r autotile.kwinscript pkg`

After this, I was able to install `v1.3.0`.

However, tiling is not working in this `v1.3.0`. I don't know whether it is because of the new version or because of how I installed it.

I had to revert back to `v1.2.2` through `no-activities` branch.

btw, I did a clean install of `v1.3.0` instead of `git pull`. Also, `Makefile` is working properly for `v1.2.2`

**Comment by zeroxoneafour** [comment]
1.3.0 is beta beta and completely broken rn. I tried to rewrite it for activities support and at this point I may just say activities are unsupported.

As for the makefile, I don't know. The autotile.kwinscript provided in the repo should be up to date though, so you dont need to rebuild if your not changing the code. The makefile does work for me though.

**Comment by rstrube** [comment]
You need to install typescript.  On arch I had to `pacman -S typescript`, this provides the `tsc` command which the makefile refers to.

**Comment by zeroxoneafour** [comment]
Yeah you need to install typescript to compile it. Closing this as completed
