### ISSUE TITLE
Pop up window are tiled

### ISSUE THREAD

**Issue by Francesco7602** [zeroxoneafour/kwin-autotile#5]
Sorry to bother you again, but I notice that in settings if a pop-up window appear, is tiled and not floating.
Like that 
![immagine](https://user-images.githubusercontent.com/43477782/226545674-f5abc94d-d16d-43db-aaa6-b0363b91b51c.png)
I don't know if I had to insert something in the whitelist, I try but that window is see as "setting" and i can't put setting in the whitelist because it'll make all setting floating, not only the pop.up one.

**Comment by zeroxoneafour** [comment]
I know about this issue but I don't know if KDE on Wayland supports EWMH hints, including the _NET_WM_WINDOW_TYPE that the scripts need to figure out what type of window a selected window is and whether it's a pop up or not. Most windows I've inspected have had all properties set, so they get tiled no matter what. I'll test it later and see what I can do.

**Comment by zeroxoneafour** [comment]
I found out that KWin on Wayland has no support for EWMH outside of knowing that Plasmashell is a desktop. However, pure Wayland clients have xdg-shell support, which tells whether a window is normal or a popup. The script now does not tile windows that are marked as popups, however some windows (including lots of systemsettings windows) are not marked this way. v1.0.1 will not fix that specific issue, but it will fix most other similar issues with non XWayland apps.

**Comment by Francesco7602** [comment]
So, there is nothing that can be done?
Or we have to wait that Wayland include support for EWMH?

**Comment by zeroxoneafour** [comment]
If the specific popup in question still doesn't work, then I don't know if there's more that I can do on the scripting side. v1.0.1 works for me for supported popups though.

**Comment by Francesco7602** [comment]
Yeah, for supported popuo it works for me too.
the problem is with the setting popup, with them don't work

**Comment by Francesco7602** [comment]
I'm sorry, but now for some strange reason it have start working fine.
Maybe it was my fault, i didn't reboot when i update the script

**Comment by zeroxoneafour** [comment]
That's good. Closing as completed
