### ISSUE TITLE
Make it work with X11 ?   And other things... 

### ISSUE THREAD

**Issue by linuxguy123** [zeroxoneafour/kwin-autotile#6]
What would it take to make it work with X11 ?  (I haven't looked at the source.)

Would be nice to save layouts and be able to recall them.

Would be nice to use a different layout on each virtual desktop.

**Comment by zeroxoneafour** [comment]
In theory, it works with X11. I don't know what else is needed to make it work, and Bismuth works well on X11 with some window rules anyway.

Both of the other features need to be integrated into KWin, and can't be done with my script.

I'm going to mark this issue as closed, X11 support isn't really on the roadmap but may be added by chance.

**Comment by Thaodan** [comment]
> In theory, it works with X11. I don't know what else is needed to make it work, and Bismuth works well on X11 with some window rules anyway.

Just to clarify Bismuth is not working on X11 even with those Window rules (unless I did something wrong), 
changing layouts and enforcing of tiling doesn't work.
