### ISSUE TITLE
Xorg support?

### ISSUE THREAD

**Issue by Mithras** [zeroxoneafour/kwin-autotile#8]
Can you please elaborate why it doesn't work on Xorg? If it's a Plasma problem maybe create an issue there? I can't use Wayland because I have NVidia.

**Comment by zeroxoneafour** [comment]
I really cannot elaborate on why it doesn't work. Theoretically speaking, scripts should behave the same as they both run on the same API (functions, objects, etc). Just like how Bismuth works on Xorg but not Wayland sometimes... it's weird.

Wayland with Nvidia works well for me with 5.27, only bug I've encountered is that the Night Shift does not work.

**Comment by zeroxoneafour** [comment]
If you want autotiling on Xorg, Bismuth is a better alternative. I've heard you can set a window rule telling all windows to "Ignore requested geometry" and make an exception for apps that need it like Krunner. This should make it work. Now that I think of it, this may make this script work as well but idk.
