### ISSUE TITLE
New windows do no get autotiled

### ISSUE THREAD

**Issue by RCorvi** [zeroxoneafour/kwin-autotile#9]
Hi, let me open by thanking you for this amazing script. Since the switch to plasma 5.27, Bismuth was not working anymore on wayland and that was really hindering my workflow, but this script manage to fill that void. With that said, I have been having a bug where new windows being opened are not tiled but are float windows by default. However, if I use the shortcut they are tiled according to the current layout.  I am on the latest plasma 5.27.3.  I do not know what further information it may need necessary to analyze the issue.

**Comment by zeroxoneafour** [comment]
Can you enable debug mode in the settings, logout and log back in, try to do a few actions, then run the following command -
```
journalctl --user --no-pager -e | grep "Autotile DBG"
```
and give me the output?

**Comment by RCorvi** [comment]
Sorry for the late reply. I have done what you asked, just spawned a few konsoles, tiled them, changed desktop then opened this firefox instance. The output of the command is this:
`kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Desktop changed on org.kde.konsole from desktop 1
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1170]: js: Autotile DBG: Retiling client firefox
kwin_wayland[1170]: js: Autotile DBG: Client firefox minimized
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Config Updated
kwin_wayland[1092]: js: Autotile DBG: useWhitelist == true
kwin_wayland[1092]: js: Autotile DBG: blacklist == krunner,yakuake
kwin_wayland[1092]: js: Autotile DBG: tilePopups == false
kwin_wayland[1092]: js: Autotile DBG: borders == 1
kwin_wayland[1092]: js: Autotile DBG: invertInsertion == false
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Desktop changed on org.kde.konsole from desktop 1
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Retiling client firefox
kwin_wayland[1092]: js: Autotile DBG: Client firefox minimized
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.konsole
kwin_wayland[1092]: js: Autotile DBG: Client firefox unminimized`

I don't what actions could have been helpful. If there is anything else that could be useful let me know.

**Comment by RCorvi** [comment]
Sorry for the late reply. I have done what you have asked, just opened a few console instances, tiled them, moved one to a different desktop, then spawned this firefox instance. I don't know what actions could have been helpful. If there is anything else that could be useful let me know. The output of the command is the following:
```
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole   
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Desktop changed on org.kde.konsole from desktop 1    
kwin_wayland[1170]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole    
kwin_wayland[1170]: js: Autotile DBG: Retiling client firefox    
kwin_wayland[1170]: js: Autotile DBG: Client firefox minimized    
kwin_wayland[1170]: js: Autotile DBG: Removing client org.kde.konsole    
kwin_wayland[1092]: js: Autotile DBG: Config Updated    
kwin_wayland[1092]: js: Autotile DBG: useWhitelist == true    
kwin_wayland[1092]: js: Autotile DBG: blacklist == krunner,yakuake    
kwin_wayland[1092]: js: Autotile DBG: tilePopups == false    
kwin_wayland[1092]: js: Autotile DBG: borders == 1    
kwin_wayland[1092]: js: Autotile DBG: invertInsertion == false    
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1092]: js: Autotile DBG: Retiling client org.kde.konsole    
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.konsole    
kwin_wayland[1092]: js: Autotile DBG: Desktop changed on org.kde.konsole from desktop 1    
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.konsole      
kwin_wayland[1092]: js: Autotile DBG: Retiling client firefox      
kwin_wayland[1092]: js: Autotile DBG: Client firefox minimized      
kwin_wayland[1092]: js: Autotile DBG: Removing client org.kde.        
kwin_wayland[1092]: js: Autotile DBG: Client firefox unminimized    
```

**Comment by zeroxoneafour** [comment]
Go to the script settings and turn use whitelist off, then logout and log back in

**Comment by RCorvi** [comment]
Thank you, it was indeed that the issue. I do not remember ever setting the flag for that option, I must have done it accidentally. Anyhow, thank you again for your help and I apologize for bothering you with such a trivial problem.
